# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a1106a7eda5c23bd875ba37845784f1c78f2a8223115f86870cd0d9031569af1961f3f04a2181ed8a442f8e385d4dad9dedd69122a636844cd2032378aa7e96

test:
  secret_key_base: e8450a78e1f69fa9341ee654a52d88b9afadd46f494be4efb0bd0b3ac046a335e432c6e9e0346e1be170594e984a088e187976ebcc1824463a6ae100195af5d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
